import mongoose from "mongoose";

/**
 * Solution document — stores a full worked solution as markdown text.
 *
 * The `content` field holds the entire solution generated by the AI
 * (or written manually) in Markdown format, exactly as produced —
 * including equations, steps, reasoning, and final answer.
 *
 * Owns the reference back to its parent Question via `questionId`.
 * One question can have multiple Solution documents pointing at it.
 */
const solutionSchema = new mongoose.Schema({
  questionId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "QuestionBank",
    required: true,
  },

  content: {
    type: String,
    required: true,
  },

  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
  },

  createdAt: {
    type: Date,
    default: Date.now,
  },
});

export const Solution = mongoose.model("Solution", solutionSchema);
